export const PERMISSIONS = {
  LIST_TRANSITORY_DOCUMENTS: 'LIST_TRANSITORY_DOCUMENTS',
  VIEW_TRANSITORY_DOCUMENTS: 'VIEW_TRANSITORY_DOCUMENTS',
  DOWNLOAD_TRANSITORY_DOCUMENTS: 'DOWNLOAD_TRANSITORY_DOCUMENTS',
} as const;
