FROM mcr.microsoft.com/dotnet/sdk:9.0

ENV ASPNETCORE_ENVIRONMENT='Production'
ENV ASPNETCORE_URLS='http://+:5001'
ENV DOTNET_STARTUP_PROJECT='./transitory-documents-api/transitory-documents-api.csproj'
ENV DOTNET_USE_POLLING_FILE_WATCHER 1

RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg