region              = "ca-central-1"
test_s3_bucket_name = "jasper-test-s3-bucket-test"
web_subnet_names    = ["Web_Test_aza_net", "Web_Test_azb_net"]
app_subnet_names    = ["App_Test_aza_net", "App_Test_azb_net"]
data_subnet_names   = ["Data_Test_aza_net", "Data_Test_azb_net"]
openshift_iam_user  = "openshiftusertest"
iam_user_table_name = "BCGOV_IAM_USER_TABLE"
lb_name             = "default"
rds_db_ca_cert      = "rds-ca-rsa2048-g1"
cert_domain_name    = "*.example.ca"
delete_protection_enabled = false
mongo_node_count    = 1
mongo_instance_type = "db.t3.medium"
mongousername       = "adminmongo"