name: Build and Test API

on:
  pull_request:
    branches:
      - master
    paths:
      - 'api/**'
      - 'db/**'
      - 'models/**'
      - 'core/**'
      - 'cso-client/**'
      - 'dars-client/**'
      - 'jc-interface-client/**'
      - 'pcss-client/**'
      - 'transitory-documents-client/**'
      - 'tests/**'

  workflow_dispatch:

env:
  WORKING_DIRECTORY: .

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      packages: read

    strategy:
      matrix:
        dotnet-major-version: [10]
        dotnet-minor-version: [0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Building Web codebase
        uses: ./.github/workflows/actions/build-api
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          dotnet_version: ${{ matrix.dotnet-major-version }}.${{ matrix.dotnet-minor-version }}
