name: Build and Test transitory-documents-api

permissions:
  contents: read

on:
  pull_request:
    branches:
      - master
    paths:
      - 'transitory-documents-api/**'
      - 'transitory-documents-client/**'
      - 'models/**'
      - 'core/**'

  workflow_dispatch:

env:
  WORKING_DIRECTORY: .

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-major-version: [10]
        dotnet-minor-version: [0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Building transitory documents codebase
        uses: ./.github/workflows/actions/build-transitory-documents-api
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          dotnet_version: ${{ matrix.dotnet-major-version }}.${{ matrix.dotnet-minor-version }}
