name: Deploy Web to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'lz-dev'
        type: choice
        options:
          - lz-dev
          - lz-test
          - lz-prod
          - dev
          - test
          - prod

env:
  WORKING_DIRECTORY: ./web
  WEB_IMAGE_NAME: web
  WEB_RUNTIME_IMAGE_NAME: web-runtime
  WEB_ARTIFACTS_IMAGE_NAME: web-artifacts
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper
  WEB_BASE_HREF: /

jobs:
  build:
    name: Build, Create and Push Image
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.IMAGE_TAG }}

    strategy:
      matrix:
        node-major-version: [22]
        node-minor-version: [x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Building Web codebase
        uses: ./.github/workflows/actions/build-web
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          node_version: ${{ matrix.node-major-version }}.${{ matrix.node-minor-version }}

      - name: Log in to the GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Image Tag
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${{ github.ref_name }}"
            echo "IMAGE_TAG=${VERSION#v}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
        with:
          driver: docker

      - name: Setup ${{ env.WEB_IMAGE_NAME }} Image Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.WEB_IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.IMAGE_TAG }}

      - name: Build ${{ env.WEB_IMAGE_NAME }} image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true
          context: .
          file: ./docker/web/Dockerfile.release
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          build-args: |
            NODE_VERSION=${{ matrix.node-major-version }}
            WEB_BASE_HREF=${{ env.WEB_BASE_HREF }}
            NGINX_RUNTIME_SRC=../../docker/nginx-runtime
            VUE_ON_NGINX_SRC=../../docker/vue-on-nginx
            WEB_SRC=../../web
            VITE_ENV=${{ github.event.inputs.environment }}

  deploy2env:
    name: Deploy to ENV
    needs: build
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Deploy to ${{ env.ENVIRONMENT }}
        uses: ./.github/workflows/actions/deploy-app
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws_account: ${{ vars.AWS_ACCOUNT }}
          region: ${{ vars.AWS_REGION }}
          app_name: ${{ vars.APP_NAME }}
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
          github_image_repo: ${{ env.GITHUB_IMAGE_REPO }}
          image_name: ${{ env.WEB_IMAGE_NAME }}
          tier_name: web
          image_tag: ${{ needs.build.outputs.image_tag }}
