name: Deploy API to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'lz-dev'
        type: choice
        options:
          - lz-dev
          - lz-test
          - lz-prod
          - dev
          - test
          - prod

env:
  WORKING_DIRECTORY: .
  IMAGE_NAME: api
  GITHUB_IMAGE_REPO: ghcr.io/bcgov/jasper

jobs:
  build:
    name: Build, Create and Push Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.version.outputs.IMAGE_TAG }}

    strategy:
      matrix:
        dotnet-major-version: [10]
        dotnet-minor-version: [0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Build API codebase
        uses: ./.github/workflows/actions/build-api
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}
          dotnet_version: ${{ matrix.dotnet-major-version }}.${{ matrix.dotnet-minor-version }}

      - name: Log in to the GHCR
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Image Tag
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${{ github.ref_name }}"
            echo "IMAGE_TAG=${VERSION#v}" >> $GITHUB_OUTPUT
            echo "RELEASE_VERSION=${VERSION#v}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            echo "RELEASE_VERSION=" >> $GITHUB_OUTPUT
          fi

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.IMAGE_TAG }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build and Push Image to ghcr.io
        id: build_image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          push: true
          context: .
          file: ./docker/api/Dockerfile.release
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          load: true
          build-args: |
            dotnet_version=${{ matrix.dotnet-major-version }}.${{ matrix.dotnet-minor-version }}
            RELEASE_VERSION=${{ steps.version.outputs.RELEASE_VERSION }}

  deploy2env:
    name: Deploy to ENV
    needs: build
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    permissions:
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.ref }}

      - name: Deploy to ${{ env.ENVIRONMENT }}
        uses: ./.github/workflows/actions/deploy-app
        with:
          environment: ${{ env.ENVIRONMENT }}
          aws_account: ${{ vars.AWS_ACCOUNT }}
          region: ${{ vars.AWS_REGION }}
          app_name: ${{ vars.APP_NAME }}
          aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
          ghcr_token: ${{ secrets.GITHUB_TOKEN }}
          github_image_repo: ${{ env.GITHUB_IMAGE_REPO }}
          image_name: ${{ env.IMAGE_NAME  }}
          tier_name: api
          image_tag: ${{ needs.build.outputs.image_tag }}
