name: Publish Openshift Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'docker/openshift/**'
      - 'openshift/**'

env:
  GITHUB_IMAGE_REPO: ghcr.io/devinleighsmith/jasper
  SRC_PATH: ../../docker/openshift

permissions:
  id-token: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    name: Deploy Images
    strategy:
      matrix:
        dockerfile-image:
          - Dockerfile=./docker/openshift/Dockerfile.sync-secrets,image=sync-secrets
          - Dockerfile=./docker/openshift/Dockerfile.generate-mongo-tls,image=generate-mongo-tls
          - Dockerfile=./docker/openshift/Dockerfile.update-aws-creds,image=update-aws-creds

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Log in to the GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          driver: docker

      - name: Parse Dockerfile and Image Name
        id: parse
        run: |
          echo "Dockerfile: ${{ matrix.dockerfile-image }}"
          DOCKERFILE=$(echo "${{ matrix.dockerfile-image }}" | cut -d',' -f1 | cut -d'=' -f2)
          IMAGE=$(echo "${{ matrix.dockerfile-image }}" | cut -d',' -f2 | cut -d'=' -f2)
          echo "DOCKERFILE=$DOCKERFILE" >> $GITHUB_ENV
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Setup Image Metadata
        id: meta
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ env.GITHUB_IMAGE_REPO }}/${{ env.IMAGE }}
          tags: |
            type=raw,value=latest

      - name: Build and Push Image to ghcr.io
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          provenance: false
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ env.DOCKERFILE }}
          build-args: |
            SRC=${{ env.SRC_PATH }}
