FROM centos/nodejs-10-centos7:10
ARG WEB_BASE_HREF
ENV WEB_BASE_HREF="$WEB_BASE_HREF"
ENV WEB1_BASE_HREF="$WEB_BASE_HREF"
WORKDIR /opt/app-root/src
COPY . .
RUN echo "$WEB1_BASE_HREF"
RUN echo "$WEB_BASE_HREF"
RUN npm install
RUN chmod -R 775 /opt/app-root/src
RUN npm run build 